### PR TITLE
feat: support Microsoft Edge Browser

### PR DESCRIPTION
**Pull request by imkerberos**

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Hey, thanks for the PR but it seems that you've made a lot of changes unrelated to the topic of PR. Also, this project uses [`stylua`](https://github.com/JohnnyMorganz/StyLua) for formatting with [this configuration.](https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/main/stylua.toml)

Please make the necessary changes and then I will review the PR.

**Comment by imkerberos** [comment]
@dhruvmanila I have formatted the PR, please review it. thank you.

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
This looks good!

One minor nitpick: Please change the name to just `edge`, there's no need to add the company name. I will be doing the same for `google_chrome` as well.

Also, can you tell me which OS you've tested this on?

**Comment by imkerberos** [comment]
I have renamed "microsoft_edge" to "edge" and tested it on MacOS.

**Review by dhruvmanila — APPROVED** [review]

**Pull request merged**
